if [ $(tput colors) -gt 8 ]; then typeset -g ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
else typeset -g ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=0,bold'
fi

typeset -ga ZSH_AUTOSUGGEST_STRATEGY
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

ZSH_AUTOSUGGEST_USE_ASYNC=1

typeset -ga ZSH_AUTOSUGGEST_ACCEPT_WIDGETS
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
	end-of-line
)

ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(
  forward-char
  forward-word
)
